In [1]:
import numpy as np
from dgeba_hardener.trajectory_matching_develop import TrajectoryMatching

def basis_function(x, p):
    return np.sign(x) * np.abs(x) ** p

outfile = "/home/markjenei/polymerisation-coarse-graining/dgeba_hardener/hardener/lj_trajectory_match_test.out"
params = range(0, -15, -1)
simulation_timestep = 0.5
# These parameters affect the accuracy of the fit. 'steps' = {'NVE': 2/500, 'NpT': 1/500}
steps = 1
timesteps_in_fit = 10

proc = TrajectoryMatching(outfile_path=outfile, simulation_timestep=simulation_timestep, cutoff=15,
                      basis=basis_function, basis_parameters=params,
                      evrey_n_from_output=steps, timesteps_in_fit=timesteps_in_fit, system_style='molecular')

#test = proc.reduce_to_centre_of_mass(1)

Reading data	

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [2]:
a = [[0,1,2,3,4], [10,11,12,13,14], [20,21,22,23,24]]
b = [1,1,2,2,3]
a, b = np.array(a), np.array(b)
print(a * b)

[[ 0  1  4  6 12]
 [10 11 24 26 42]
 [20 21 44 46 72]]
